/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author isabe
 */
public class frmUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmUsuarios
     */
    public frmUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblIngresarDatos = new javax.swing.JLabel();
        lblIdUsuario = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblTipoUsuario = new javax.swing.JLabel();
        lblActivo = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtIdUsuario = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();
        lblConfirmarContraseña = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        cbActivo = new javax.swing.JCheckBox();
        cbTipoUsuario = new javax.swing.JComboBox<>();
        lblBusqueda = new javax.swing.JLabel();
        lblBusquedaPorNomUsuario = new javax.swing.JLabel();
        txtBusquedaPorNomUsuario = new javax.swing.JTextField();
        btnBuscarPorNomUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsuarios = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        txtConfirmarContraseña = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Crear y modificar usuarios");

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setText("Información del usuario ");

        lblIngresarDatos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIngresarDatos.setText("Ingresar datos: ");

        lblIdUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblIdUsuario.setText("Id del usuario: ");

        lblNombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNombreUsuario.setText("Nombre de usuario:");

        lblContraseña.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblContraseña.setText("Contraseña:");

        lblTipoUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTipoUsuario.setText("Tipo de usuario:");

        lblActivo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblActivo.setText("¿Activo? :");

        lblCorreo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCorreo.setText("Correo: ");

        txtIdUsuario.setEditable(false);
        txtIdUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtNombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });

        lblConfirmarContraseña.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblConfirmarContraseña.setText("Confirmar contraseña:");

        txtCorreo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        cbActivo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbActivo.setText("Sí ");
        cbActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActivoActionPerformed(evt);
            }
        });

        cbTipoUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Encargado de compras", "Encargado de bodega", " " }));

        lblBusqueda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBusqueda.setText("Búsqueda:");

        lblBusquedaPorNomUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblBusquedaPorNomUsuario.setText("Búsqueda por nombre de usuario: ");

        btnBuscarPorNomUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBuscarPorNomUsuario.setText("Buscar");

        tableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableUsuarios);

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");

        btnRefrescar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRefrescar.setText("Refrescar");

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEliminar.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIngresarDatos)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdUsuario)
                                    .addComponent(lblNombreUsuario)
                                    .addComponent(lblContraseña)
                                    .addComponent(lblConfirmarContraseña)
                                    .addComponent(lblTipoUsuario)
                                    .addComponent(lblCorreo)
                                    .addComponent(lblActivo))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnGuardar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEditar))
                                    .addComponent(txtIdUsuario)
                                    .addComponent(txtNombreUsuario)
                                    .addComponent(txtCorreo)
                                    .addComponent(cbActivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbTipoUsuario, 0, 164, Short.MAX_VALUE)
                                    .addComponent(txtContraseña)
                                    .addComponent(txtConfirmarContraseña))))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBusqueda)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBusquedaPorNomUsuario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBusquedaPorNomUsuario)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscarPorNomUsuario))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnRefrescar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)))))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngresarDatos)
                    .addComponent(lblBusqueda))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdUsuario)
                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBusquedaPorNomUsuario)
                    .addComponent(txtBusquedaPorNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPorNomUsuario))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreUsuario)
                            .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContraseña)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblConfirmarContraseña)
                            .addComponent(txtConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoUsuario)
                            .addComponent(cbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblActivo)
                            .addComponent(cbActivo))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorreo)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnRefrescar)
                    .addComponent(btnGuardar)
                    .addComponent(btnEditar))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void cbActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbActivoActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUsuariosMouseClicked
        // TODO add your handling code here:
        try {
            int fila = tableUsuarios.getSelectedRow();
            txtIdUsuario.setText(tableUsuarios.getValueAt(fila, 0).toString());
            txtNombreUsuario.setText(tableUsuarios.getValueAt(fila, 1).toString());
            txtContraseña.setText(tableUsuarios.getValueAt(fila, 2).toString());
            txtConfirmarContraseña.setText(tableUsuarios.getValueAt(fila, 2).toString());
            cbTipoUsuario.setSelectedItem(tableUsuarios.getValueAt(fila, 3).toString());
            cbActivo.setSelected(Boolean.parseBoolean(tableUsuarios.getValueAt(fila, 4).toString()));
            txtCorreo.setText(tableUsuarios.getValueAt(fila, 5).toString());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tableUsuariosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarPorNomUsuario;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnRefrescar;
    public javax.swing.JCheckBox cbActivo;
    public javax.swing.JComboBox<String> cbTipoUsuario;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblActivo;
    public javax.swing.JLabel lblBusqueda;
    public javax.swing.JLabel lblBusquedaPorNomUsuario;
    public javax.swing.JLabel lblConfirmarContraseña;
    public javax.swing.JLabel lblContraseña;
    public javax.swing.JLabel lblCorreo;
    public javax.swing.JLabel lblIdUsuario;
    public javax.swing.JLabel lblIngresarDatos;
    public javax.swing.JLabel lblNombreUsuario;
    public javax.swing.JLabel lblTipoUsuario;
    public javax.swing.JLabel lblTitle;
    public javax.swing.JTable tableUsuarios;
    public javax.swing.JTextField txtBusquedaPorNomUsuario;
    public javax.swing.JPasswordField txtConfirmarContraseña;
    public javax.swing.JPasswordField txtContraseña;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtIdUsuario;
    public javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
